# Generated by Django 4.0.5 on 2022-06-26 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_groupchatrecruitment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 17, 19, 57, 426856)),
        ),
        migrations.AlterField(
            model_name='groupchatrecruitment',
            name='explanation',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='individualchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 17, 19, 57, 426139)),
        ),
        migrations.AlterField(
            model_name='individualchatrecruitment',
            name='explanation',
            field=models.TextField(max_length=500),
        ),
    ]
