# Generated by Django 4.0.5 on 2022-06-26 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_groupchatrecruitment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 17, 27, 26, 13000)),
        ),
        migrations.AlterField(
            model_name='groupchatroom',
            name='group_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='individualchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 17, 27, 26, 12282)),
        ),
    ]
