# Generated by Django 4.0.5 on 2022-07-06 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_groupchatrecruitment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 15, 44, 14, 156196)),
        ),
        migrations.AlterField(
            model_name='individualchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 15, 44, 14, 155944)),
        ),
    ]
