# Generated by Django 4.0.5 on 2022-07-06 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_groupchatrecruitment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 17, 24, 44, 843863)),
        ),
        migrations.AlterField(
            model_name='individualchatrecruitment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 17, 24, 44, 843612)),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
