# Generated by Django 4.0.5 on 2022-06-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_view',
            field=models.CharField(default='recruitment', max_length=15),
        ),
    ]
