# Generated by Django 4.0.5 on 2022-06-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_view',
        ),
    ]
