# Generated by Django 4.0.5 on 2022-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_last_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='self_introduction',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='self introduction'),
        ),
    ]
